### ISSUE TITLE
[BUG] Atlas Installer Fails on MacOS Catalina

### ISSUE THREAD

**Issue by Lomdjaria1** [dessa-oss/atlas#109]
**Platform & setup**
MacOS Catalina

**Describe the bug**
Traceback (most recent call last):
  File "atlas_installer.py", line 657, in <module>
    log.info("Attempting to download the installation package from {}".format(file_url))

**To Reproduce**
Go throw installation guide

**Expected behavior**
Changes in pyinstaller.py : Use logger.info instead of log.info

**Comment by mohammedri** [comment]
Hey @Lomdjaria1 , thank you for flagging - our team is looking into it

**Comment by mohammedri** [comment]
Thank you @Lomdjaria1 , we have now fixed this issue
