### ISSUE TITLE
[Incident] Docker containers IP addresses conflict with VPN

### ISSUE THREAD

**Issue by ajesteves** [dessa-oss/atlas#113]
### Description
I have a problem with the atlas-ce-* docker containers. These container use an IP range 172.20.* that conflicts with my work VPN addresses. 

### Error
With these containers running i cann't connect from home to the machine where atlas is installed using VPN.

### Cause of issue 
The problem is due to a network interface created by atlas-ce: br-xxxxxx that uses the same IP range as my work VPN.

### Solution
Configure atlas-ce docker containers to use a different IP range.

**Comment by amackillop** [comment]
Thanks for pointing this out. IP ranges are configurable in docker so we should be able to give users the option to manually set this in case of conflicts.

**Comment by ajesteves** [comment]
Hello,
Do you know how can i solve the problem now? Remove atlas-ce containers? Remove containers and wait for new docker images that can be configured?
Thanks for your attention.

**Comment by amackillop** [comment]
The docker network is created when you run `atlas-server start`. The script that gets run is here: https://github.com/dessa-oss/atlas/blob/master/atlas_server/src/atlas-server/__main__.py and on line 244 is where the network is created. 

You can try editing the installed version of this file and add an ip range to that command. The file should be located in the site-packages directory of your wherever your virtual environment for python is located.

**Comment by amackillop** [comment]
This may be useful: https://docker-py.readthedocs.io/en/stable/api.html#docker.types.IPAMConfig

**Comment by ajesteves** [comment]
So, you suggest to add to the mentioned file (__main__.py) the following code, after installing atlas and before starting the server?
...
ipam_pool   = docker.types.IPAMPool(subnet='172.25.0.0/24', gateway='192.168.85.254')
ipam_config = docker.types.IPAMConfig(pool_configs=[ipam_pool])
self.__class__._network = self._client.networks.create (
    self.__class__._network_name,
    driver="bridge",
    ipam=ipam_config
    )
...

**Comment by amackillop** [comment]
Yes I would give that a try just make sure that you are editing the correct file that will be executed by `atlas-server`. Let me know how it goes.

**Comment by ajesteves** [comment]
Hi again,
I will try another day since the installer is not working.
It tries to download atlas version 0.1.1.dev3 that is not available on github.

**Comment by mohammedri** [comment]
Hey @ajesteves , thanks for pointing out the bug in the installer. @amackillop has fixed it in https://github.com/dessa-oss/atlas/pull/114

Can you try again?

**Comment by ajesteves** [comment]
Sure, i will try.
Thanks

**Comment by amackillop** [comment]
You should be able to edit the current installer file as well and just remove the `.dev3` part from the `build_version` if you don't want to wait for a release.

**Comment by mohammedri** [comment]
@ajesteves we just pushed a new version of the installer, so you should be able to use that. 
I hope your docker question was answered above.

Cheers
