### ISSUE TITLE
[Mac Installation] 404 Error in downloading `atlas.tgz`

### ISSUE THREAD

**Issue by cbalaf** [dessa-oss/atlas#115]
Running `python atlas_installer.py` on a Macbook gives the following error:
`Cannot download the installation package from https://github.com/dessa-oss/atlas/releases/download/0.1.1.dev3/atlas.tgz.`. I downloaded the `atlas_installer.py` from https://github.com/dessa-oss/atlas/releases

**Comment by mohammedri** [comment]
Hey @cbalaf ! We are working on fixing this issue, in the meanwhile here is a quick workaround:
1. Open up `atlas_installer.py` and change the version `0.1.1.dev3` to `0.1.1`

**Comment by cbalaf** [comment]
Thanks for the quick reply! I changed line 18 of `atlas_installer.py` to `0.1.1` but, unfortunately, I'm getting the same error

**Comment by amackillop** [comment]
It should be 0.1.0.

**Comment by cbalaf** [comment]
That did it - thanks so much!
