### ISSUE TITLE
Save artifact on remote server

### ISSUE THREAD

**Issue by SebastianGergen** [dessa-oss/atlas#120]
**Platform & setup**
Ubuntu 18.04 Server, Atlas on server and job execution via remote laptop.

**Describe the bug**
When I schedule and run a job from remote on my atlas server, and I save artifacts (e.g. readme.txt), and I open the job details on the atlas GUI, I am forwarded to "http://localhost:5557/archive/....." instead of "http://MASTER-IP:5557/archive/.....", thus the file is not found, until I manually change the IP.
Either I missed something in the configuration of my server or there might be a little bug.

**Expected behavior**
the page that opens under the job details should open on the master servers IP, not on localhost, if atlas is executing scheduled jobs in an on premise installation.

**Comment by mohammedri** [comment]
CC: @pippinlee

**Comment by shazraz** [comment]
Hello @SebastianGergen, you can use the the `-s` option when starting Atlas server to specify the IP of the host to be used. 

Here's what this might look like: `atlas-server start -s 192.168.0.10` where `192.168.0.10` is the IP of the machine where you are running Atlas.

**Comment by SebastianGergen** [comment]
Thank you, @shazraz. This seems to work. Is this mentioned in the documentation?

**Comment by pippinlee** [comment]
Good point @SebastianGergen, we don't currently have explicit documentation on the `atlas-start` CLI, just the `foundations` CLI. For now you can use `atlas-server start --help` to understand the different commands available, and I'll make a ticket for us document these commands on the docs.

Going to close this for now, but feel free to update if you see any related issues to this.
