### ISSUE TITLE
Syntax error installer file line 396

### ISSUE THREAD

**Issue by Julien-Bernardo** [dessa-oss/atlas#124]
**Platform & setup**
Mac OS

**Describe the bug**
Syntax error installer file line 396.

**To Reproduce**
1. created 'Atlas' environment with conda in terminal
2. ran the atlas_installer.py

**Expected behavior**
Installation to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/57379630/78929163-e4fd8580-7a6f-11ea-813a-81d62938115f.png)

**Additional context / Stacktrace**

**Comment by amackillop** [comment]
I confirmed that this is an issue with Python 2 being used and the fix has been pushed to master. Than you @Julien-Bernardo for bringing this to our attention.
