### ISSUE TITLE
Setting up an internal Atlas Cluster

### ISSUE THREAD

**Issue by mohammedri** [dessa-oss/atlas#128]

**Comment by shazraz** [comment]
@cindyzczhao let me know if you're looking for support.

**Comment by mohammedri** [comment]
@cindyzczhao just checking in to see you are 👍 , did you have an expected timeline of completion on this? Any roadblocks we should be aware of?

**Comment by cindyzczhao** [comment]
@mohammedri to copy over the list of tasks left to do that @shazraz put in the risk ticket:

 - Upload SSL certificate when this ticket is complete
 - File NETENG tickets to open firewall rules for redis, auth proxy and scheduler
 - Enable and test IAP for Atlas. Try following Symphony onboarding guide and this
 - Forward the port for the archive server in the load balancer and do other firewall things to ensure user can download artifacts from GUI
 - Make sure we can hit Atlas and track experiments from a Managed Notebook instance.
 - Celebrate.

Some of these are filed tickets which might take a few days to be resolved, but hopefully this will be complete soon.
