### ISSUE TITLE
[BUG] Install failed on GCP when following instructions from docs

### ISSUE THREAD

**Issue by shazraz** [dessa-oss/atlas#132]
The documentation [here](https://docs.atlas.dessa.com/en/latest/atlas-on-gcp/) provides installation instructions for GCP. 

These lines result in a 404
``` 
wget https://github.com/dessa-oss/atlas/releases/latest/download/atlas_installer.py   
wget https://github.com/dessa-oss/atlas/releases/latest/download/atlas.tgz
```
because the release is not tagged `latest`. The workaround to fix this right now is to replace `latest` with the current release version from [here](https://github.com/dessa-oss/atlas/releases).

**Comment by nicknagi** [comment]
Retagged 0.1.1 as latest on Github
