### ISSUE TITLE
How to start Atlas

### ISSUE THREAD

**Issue by ak-kuznetsov** [dessa-oss/atlas#189]
After completing the installation section, I validated that I am in the same python environment that was used to run the installation script and then run **atlas-server start**. 
Can you please explain what is **atlas-server start** and where can I get it?
Thank you

**Comment by mohammedri** [comment]
Hey @ak-kuznetsov , I am curious are you still using Atlas or have you found an alternative?

**Comment by ak-kuznetsov** [comment]
Hi @mohammedri , still using

**Comment by mohammedri** [comment]
Glad to hear that, how did you discover Atlas? @ak-kuznetsov
