### ISSUE TITLE
[BUG] Putting colons in metric/parameter/tag keys breaks the REST API

### ISSUE THREAD

**Issue by shazraz** [dessa-oss/atlas#96]
**Describe the bug**
This bug potentially applies to any piece of information we store and retrieve from redis. Essentially, there are places in the project where values are stored in redis in the form `foo:bar`. On retrieval, these values are separated by naively splitting on the colon and unpacking into variables.

For example, from `project_metrics_controller` in `_project_metrics`, there's a line like
```python
foo, bar = some_value_from_redis.decode().split(':')
```

This means that if `foo` or `bar` happens to have a colon in it, the above line would cause an unpacking error. One of such cases is if a metric key has a colon in it.

**To Reproduce**
1. Submit a job with the following line in it
```python
foundations.log_metric('fo:o', 1)
```
2. Hit the `/overview_metrics` endpoint. This will cause a 500.

**Expected behaviour**
We should be able to handle any kind of information that's being stored in redis to have a colon in it. Another idea is to prevent the user from using colons altogether.

**Comment by nicknagi** [comment]
Previous commit should have fixed this bug. 

In the `project_metrics.py` file which is responsible for saving the metric in redis:

        from foundations_internal.fast_serializer import serialize

        project_key = f'projects:{message["project_name"]}:metrics'
        metric_key = f'{message["job_id"]}:{message["key"]}'
        value = (timestamp, message['value'])

        self._redis.hset(project_key, metric_key, serialize(value))

`metric_key = f'{message["job_id"]}:{message["key"]}'` has the key seperated by a colon from the job_id, thus if we split on the first colon then we can guarantee that the first half is the job_id and the second the key therefore allowing the key to have colons (and any other characters). The previous commit should reflect this change.
